# Build and Push Docker Image to GHCR
# 
# Setup Instructions:
# 1. Go to GitHub -> Settings -> Developer settings -> Personal access tokens -> Tokens (classic)
# 2. Generate new token with 'write:packages' and 'read:packages' permissions
# 3. Add token as repository secret named 'GHCR_TOKEN'
# 4. Alternatively, ensure GITHUB_TOKEN has package write permissions enabled

name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Verify configuration
      run: |
        echo "Authenticated as: ${{ github.actor }}"
        echo "Registry: ${{ env.REGISTRY }}"
        echo "Image name: ${{ env.IMAGE_NAME }}"
        echo "Repository: ${{ github.repository }}"

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Debug metadata
      run: |
        echo "Generated tags: ${{ steps.meta.outputs.tags }}"
        echo "Generated labels: ${{ steps.meta.outputs.labels }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: |
          ${{ steps.meta.outputs.labels }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.description=Document Processing Service - Flask microservice for converting documents to text
          org.opencontainers.image.licenses=MIT
          
